--USE myFictionalBusiness;
--GO
--Alter TABLE Customers WITH CHECK
--ADD CONSTRAINT FK_ZipCode FOREIGN KEY(ZipCode) REFERENCES ZipCode(ZipCode)
--ON UPDATE CASCADE
--GO
--ALTER TABLE Orders WITH CHECK
--ADD CONSTRAINT FK_RetailerID FOREIGN KEY(RetailerID) REFERENCES Retailers(RetailerID)
--ON UPDATE CASCADE
--Go
ALTER TABLE Orders with CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
ON UPDATE CASCADE
GO
/*ALTER TABLE OrderDetails with CHECK
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(OrderID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE OrderDetails with check
ADD CONSTRAINT FK_InventoryID FOREIGN KEY(InventoryID) REFERENCES Inventory(InventoryID)
ON UPDATE CASCADE
GO*/